# Project
version=7.0.0
group=com.mrbysco.justenoughprofessions

# Common
minecraft_version=1.21.8

# NeoForge
neo_version=21.8.23
neogradle.subsystems.parchment.minecraftVersion=1.21.8
neogradle.subsystems.parchment.mappingsVersion=2025.07.20
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.130.0+1.21.8
fabric_loader_version=0.16.14

# Mod options
mod_name=JustEnoughProfessions
mod_author=Mrbysco
mod_id=justenoughprofessions

#Publishing
curseforge_id=417645
modrinth_id=kB56GtWA

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
jei_version=24.0.0.2